### ISSUE TITLE
Bundled NPM not working when no internet.

### ISSUE THREAD

**Issue by iambpn** [moonrepo/tools#12]
When NPM is set to use bundled. It tried to download the Node release JSON file to search for bundled NPM version. This causes error when internet connection is not available.

**Solution**
One solution is to cache the response of Node release JSON and use the same file to detect npm version when internet connection is unavailable.

![image](https://github.com/user-attachments/assets/b94ae2c5-0fcc-4be4-8624-3927ab449382)

**Comment by iambpn** [comment]
I am not a Rust user, but if this solution sounds okay, then I can submit the PR for this.

**Comment by milesj** [comment]
Caching these will be tricky since the requests happen in WASM. I'll look into it.

**Comment by iambpn** [comment]
thanks @milesj

**Comment by milesj** [comment]
Added caching in proto v0.42.
