### ISSUE TITLE
The installation of "Anaconda3-2024.06-1-MacOSX-x86_64.pkg" Failed

### ISSUE THREAD

**Issue by YvesR58** [moonrepo/tools#16]
I have installed it in the past but had to re-install it due to a change of computer but in the process, I am getting a message indicating that /opt/Anaconda3 already exists (but the finder cannot find it) and it asks me to re-launch the installer and chose another destination which I tried but regardless, I am still getting the same message at the end "The Installation Failed"
(The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance)

I am running on a Mac Book Air Sonoma 14.6.1 with an Intel Graphic 617.  I also tried the other Anaconda packages suggested for Mac but the results are the same. 

Thank you for your help

**Comment by milesj** [comment]
@YvesR58 We don't support Anaconda in this repo, so I think you have the wrong location.

**Comment by YvesR58** [comment]
Thanks for the quick response.
I thought I saw some comments and issues related to Anaconda. Any suggestions?

**Comment by milesj** [comment]
Sorry I don't really know. Is this moon/proto related?
